[package]
name = "pyrust_chess"
version = "0.1.1"
edition = "2024"

[lib]
name = "pyrust_chess"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.2"
shakmaty = {git = "https://github.com/kraktus/shakmaty/", branch = "force_shredder"}
bitflags = "2"

[[bin]]
name = "test_castles"
path = "../tmp/test_castles.rs"
